# Generated by Django 5.1.7 on 2025-04-05 13:19

import django.db.models.deletion
import vending.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('model_type', models.CharField(choices=[('YOLOV5', 'YOLOv5'), ('YOLOV7', 'YOLOv7'), ('YOLOV8', 'YOLOv8'), ('YOLOV8_SEG', 'YOLOv8 Segmentation'), ('YOLOV8_POSE', 'YOLOv8 Pose')], help_text='Select the type of AI model', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(blank=True, max_length=100, null=True)),
                ('machine_code', models.CharField(max_length=50, unique=True)),
                ('machine_id', models.CharField(max_length=50, unique=True)),
                ('manufacturing_date', models.DateField(auto_now_add=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('current_slot', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_sku', models.CharField(max_length=250)),
                ('variant_type', models.CharField(max_length=250)),
                ('variant_weight', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CameraFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=100)),
                ('camera_type', models.CharField(choices=[('VALIDATION', 'Validation Camera'), ('ENTRANCE_LEFT', 'Entrance Left Camera'), ('ENTRANCE_RIGHT', 'Entrance Right Camera'), ('ENTRANCE_POS', 'Entrance POS Camera'), ('CHAMBER_TOP', 'Chamber Top Camera'), ('CHAMBER_BOTTOM', 'Chamber Bottom Camera')], help_text='Select the type of camera', max_length=50)),
                ('feed_url', models.CharField(help_text='Enter the camera feed URL or RTSP stream address', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_feeds', to='vending.machine')),
            ],
            options={
                'unique_together': {('machine', 'camera_name')},
            },
        ),
        migrations.CreateModel(
            name='MachineSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(default=vending.models.generate_license_key, editable=False, max_length=19, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('subscription_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='vending.machine')),
            ],
        ),
        migrations.CreateModel(
            name='CameraAIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.JSONField(default=dict, help_text='Model-specific configuration parameters')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vending.aimodel')),
                ('camera_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_models', to='vending.camerafeed')),
            ],
            options={
                'unique_together': {('camera_feed', 'ai_model')},
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=100)),
                ('line_coordinates', models.JSONField(help_text="Format: {'x1': 0, 'y1': 0, 'x2': 100, 'y2': 100}")),
                ('line_type', models.CharField(choices=[('entry', 'Entry Line'), ('exit', 'Exit Line'), ('counting', 'Counting Line')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='vending.camerafeed')),
            ],
            options={
                'unique_together': {('camera_feed', 'line_name')},
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100)),
                ('zone_coordinates', models.JSONField(help_text="Format: {'x1': 0, 'y1': 0, 'x2': 100, 'y2': 100}")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='vending.camerafeed')),
            ],
            options={
                'unique_together': {('camera_feed', 'zone_name')},
            },
        ),
    ]
