# Generated by Django 5.1.7 on 2025-03-13 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vending', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamberStockInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamber', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField()),
                ('created_ip', models.GenericIPAddressField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire_at', models.DateTimeField()),
                ('is_active', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('kiosk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machineid', to='vending.machine')),
            ],
        ),
        migrations.CreateModel(
            name='BDA_Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.SmallIntegerField(db_comment='1 - Validation, 2 -Receive Filled, 3 - Return Empty,4 - Return Filled')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('total_count', models.CharField(blank=True, max_length=100, null=True)),
                ('validate_data', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.SmallIntegerField(db_comment='0 - Failed, 1 - Success', null=True)),
                ('response_at', models.DateTimeField(blank=True, null=True)),
                ('txn_complete', models.SmallIntegerField(db_comment=',0- Processing , 1 - Finish', null=True)),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True)),
                ('kiosk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bdatransaction', to='vending.machine')),
                ('sku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bda_sku', to='vending.sku')),
            ],
        ),
        migrations.CreateModel(
            name='ChamberSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField()),
                ('status', models.SmallIntegerField(choices=[(0, 'Empty'), (1, 'Filled'), (3, 'SlotEmpty')])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chamber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chamberslots', to='kiosk.chamberstockinventory')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.SmallIntegerField(db_comment='1 - Empty Collect , 2 - Return Empty, 3 - Receive Filled')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('validate_data', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('response_at', models.DateTimeField(blank=True, null=True)),
                ('kiosk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customertransaction', to='vending.machine')),
                ('sku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_sku', to='vending.sku')),
            ],
        ),
        migrations.CreateModel(
            name='CylinderValidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('variant', models.CharField(blank=True, max_length=100, null=True)),
                ('validate_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('response_at', models.DateTimeField(blank=True, null=True)),
                ('kiosk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validate_empty', to='vending.machine')),
            ],
        ),
        migrations.CreateModel(
            name='DispenseFilled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('response_at', models.DateTimeField(blank=True, null=True)),
                ('kiosk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensecylinder', to='vending.machine')),
            ],
        ),
        migrations.CreateModel(
            name='EmptyCollect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tracking_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('response_at', models.DateTimeField(blank=True, null=True)),
                ('slot_id', models.CharField(blank=True, max_length=100, null=True)),
                ('chamber_id', models.CharField(blank=True, max_length=100, null=True)),
                ('kiosk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empty', to='vending.machine')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnEmpty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('response_at', models.DateTimeField(blank=True, null=True)),
                ('kiosk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returnempty', to='vending.machine')),
            ],
        ),
        migrations.CreateModel(
            name='StockInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empty_stock', models.IntegerField(default=0)),
                ('filled_stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('kiosk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_inventories', to='vending.machine')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_sku', to='vending.sku')),
            ],
        ),
        migrations.AddField(
            model_name='chamberstockinventory',
            name='stock_inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chamberinventory', to='kiosk.stockinventory'),
        ),
    ]
