# Generated by Django 5.1.7 on 2025-04-05 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bda_transactions',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bdaslot', to='kiosk.chamberslots'),
        ),
    ]
