# Generated by Django 5.1.7 on 2025-04-05 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_bda_transactions_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_transactions',
            name='ref_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer_transactions',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerslot', to='kiosk.chamberslots'),
        ),
        migrations.AddField(
            model_name='customer_transactions',
            name='status',
            field=models.SmallIntegerField(db_comment='0 - Failed, 1 - Success', null=True),
        ),
        migrations.AddField(
            model_name='customer_transactions',
            name='txn_complete',
            field=models.SmallIntegerField(db_comment=',0- Processing , 1 - Finish', null=True),
        ),
    ]
