# Generated by Django 5.1.7 on 2025-04-05 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_customer_transactions_ref_id_and_more'),
        ('vending', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamberslots',
            name='kiosk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chamber', to='vending.machine'),
        ),
    ]
