# Generated by Django 5.1.7 on 2025-06-09 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0004_chamberslots_kiosk'),
        ('vending', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamberslots',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_sku', to='vending.sku'),
        ),
    ]
